config/routes.rb
Rails.application.routes.draw do
  resources :ecom_orders
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root 'ecom_orders#index'		
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/ecom_order.rb
class EcomOrder < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/ecom_orders_controller.rb
class EcomOrdersController < ApplicationController
  before_action :set_ecom_order, only: %i[ show edit update destroy ]

  # GET /ecom_orders or /ecom_orders.json
  def index
    @ecom_orders = EcomOrder.all
  end

  # GET /ecom_orders/1 or /ecom_orders/1.json
  def show
  end

  # GET /ecom_orders/new
  def new
    @ecom_order = EcomOrder.new
  end

  # GET /ecom_orders/1/edit
  def edit
  end

  # POST /ecom_orders or /ecom_orders.json
  def create
    @ecom_order = EcomOrder.new(ecom_order_params)

    respond_to do |format|
      if @ecom_order.save
        format.html { redirect_to @ecom_order, notice: "Ecom order was successfully created." }
        format.json { render :show, status: :created, location: @ecom_order }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @ecom_order.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /ecom_orders/1 or /ecom_orders/1.json
  def update
    respond_to do |format|
      if @ecom_order.update(ecom_order_params)
        format.html { redirect_to @ecom_order, notice: "Ecom order was successfully updated." }
        format.json { render :show, status: :ok, location: @ecom_order }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @ecom_order.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /ecom_orders/1 or /ecom_orders/1.json
  def destroy
    @ecom_order.destroy
    respond_to do |format|
      format.html { redirect_to ecom_orders_url, notice: "Ecom order was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_ecom_order
      @ecom_order = EcomOrder.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def ecom_order_params
      params.require(:ecom_order).permit(:price, :item_sku, :purchase_date, :platform_order_num, :sales_channel, :status, :customer_name, :customer_state, :shipped_at, :number_of_items_shipped, :payment_method)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/ecom_orders_helper.rb
module EcomOrdersHelper
end

app/views/ecom_orders/_form.html.erb
<%= form_with(model: ecom_order) do |form| %>
  <% if ecom_order.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(ecom_order.errors.count, "error") %> prohibited this ecom_order from being saved:</h2>

      <ul>
        <% ecom_order.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :price %>
    <%= form.text_field :price %>
  </div>

  <div class="field">
    <%= form.label :item_sku %>
    <%= form.text_field :item_sku %>
  </div>

  <div class="field">
    <%= form.label :purchase_date %>
    <%= form.datetime_select :purchase_date %>
  </div>

  <div class="field">
    <%= form.label :platform_order_num %>
    <%= form.text_field :platform_order_num %>
  </div>

  <div class="field">
    <%= form.label :sales_channel %>
    <%= form.text_field :sales_channel %>
  </div>

  <div class="field">
    <%= form.label :status %>
    <%= form.text_field :status %>
  </div>

  <div class="field">
    <%= form.label :customer_name %>
    <%= form.text_field :customer_name %>
  </div>

  <div class="field">
    <%= form.label :customer_state %>
    <%= form.text_field :customer_state %>
  </div>

  <div class="field">
    <%= form.label :shipped_at %>
    <%= form.datetime_select :shipped_at %>
  </div>

  <div class="field">
    <%= form.label :number_of_items_shipped %>
    <%= form.number_field :number_of_items_shipped %>
  </div>

  <div class="field">
    <%= form.label :payment_method %>
    <%= form.text_field :payment_method %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/ecom_orders/edit.html.erb
<h1>Editing Ecom Order</h1>

<%= render 'form', ecom_order: @ecom_order %>

<%= link_to 'Show', @ecom_order %> |
<%= link_to 'Back', ecom_orders_path %>

app/views/ecom_orders/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Ecom Orders</h1>

<table id  ='ordersTable' class='table table-striped table-sm'>
  <thead>
    <tr>
      <th>Price</th>
      <th>Item sku</th>
      <th>Purchase date</th>
      <th>Platform order num</th>
      <th>Sales channel</th>
      <th>Status</th>
      <th>Customer name</th>
      <th>Customer state</th>
      <th>Shipped at</th>
      <th>Number of items shipped</th>
      <th>Payment method</th>
    </tr>
  </thead>

  <tbody>
    <% @ecom_orders.each do |ecom_order| %>
      <tr>
        <td><%= ecom_order.price %></td>
        <td><%= ecom_order.item_sku %></td>
        <td><%= ecom_order.purchase_date %></td>
        <td><%= ecom_order.platform_order_num %></td>
        <td><%= ecom_order.sales_channel %></td>
        <td><%= ecom_order.status %></td>
        <td><%= ecom_order.customer_name %></td>
        <td><%= ecom_order.customer_state %></td>
        <td><%= ecom_order.shipped_at %></td>
        <td><%= ecom_order.number_of_items_shipped %></td>
        <td><%= ecom_order.payment_method %></td>

      </tr>
    <% end %>
  </tbody>
</table>

app/views/ecom_orders/new.html.erb
<h1>New Ecom Order</h1>

<%= render 'form', ecom_order: @ecom_order %>

<%= link_to 'Back', ecom_orders_path %>

app/views/ecom_orders/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Price:</strong>
  <%= @ecom_order.price %>
</p>

<p>
  <strong>Item sku:</strong>
  <%= @ecom_order.item_sku %>
</p>

<p>
  <strong>Purchase date:</strong>
  <%= @ecom_order.purchase_date %>
</p>

<p>
  <strong>Platform order num:</strong>
  <%= @ecom_order.platform_order_num %>
</p>

<p>
  <strong>Sales channel:</strong>
  <%= @ecom_order.sales_channel %>
</p>

<p>
  <strong>Status:</strong>
  <%= @ecom_order.status %>
</p>

<p>
  <strong>Customer name:</strong>
  <%= @ecom_order.customer_name %>
</p>

<p>
  <strong>Customer state:</strong>
  <%= @ecom_order.customer_state %>
</p>

<p>
  <strong>Shipped at:</strong>
  <%= @ecom_order.shipped_at %>
</p>

<p>
  <strong>Number of items shipped:</strong>
  <%= @ecom_order.number_of_items_shipped %>
</p>

<p>
  <strong>Payment method:</strong>
  <%= @ecom_order.payment_method %>
</p>

<%= link_to 'Edit', edit_ecom_order_path(@ecom_order) %> |
<%= link_to 'Back', ecom_orders_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>DatatablesApp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div class='container-fluid'>
      <%= yield %>
    </div>
  </body>
</html>